### ISSUE TITLE
Connection refuses to load resources

### ISSUE THREAD

**Issue by tarekeldeeb** [dfletcher/tsws#2] opened 2015-09-07 13:33 UTC
Hi,
I run your script on windows using MobaXterm, cygwin-based, and I try to connect using chrome. The page loads fine, but the image is not displayed and I get the following errors at chrome.

Failed to load resource: net::ERR_CONNECTION_REFUSED http://127.0.0.1:9090/graphic.jpg
Failed to load resource: net::ERR_CONNECTION_RESET http://127.0.0.1:9090/site.js 
ContentScript.js:112 Exception in onResRdy: TypeError: Cannot read property 'htmlRes' of undefined

**Comment by dfletcher** [comment] 2015-09-07 17:55
Yep there's a note in the bugs section about Cygwin. Tearing my hair out trying to understand what's going on there, it's my primary dev platform. Been testing on an Ubuntu VM until we can squash this one! It seems like possibly an issue with nc. When I've tried to debug it it's like the requests never even appear. Anyway, rest assured, Cygwin is a priority of mine.

**Comment by dfletcher** [comment] 2015-09-08 04:50
Quick update, I've manged to patch and build the source version of `nc` from Cygwin's package manager. I'm not sure about the tools they use so I patched it by hand heh. Anyway now I have sources to do some debugging with, hopefully this will lead somewhere.

**Comment by dfletcher** [comment] 2015-09-08 05:58
Hahaha great.

So, found the spot where netcat outputs to stdout. Copied that line and also made it output to /dev/tty so I could make sure nc is ouputting all the requests.

And it started working! Working slowly, but it is working. Graphic loads, whole page looks all fine.

Um huh. Well this is weird. Timing bug somehow mitigated by the extra time it's taking to write the data to tty as well as stdout?

I'll sleep on it. Very strange.

**Comment by dfletcher** [comment] 2015-09-08 09:37
Well I stayed up and fiddled with it a while. Got one hack of a solution if you at least want to see it working (though really, really slowly).

Change the line that launches nc (it's currently line 176) to this:

```
nc -i 1 -w 9999 -kl "${host}" ${port}
```

The -w 9999 sets the timeout of poll() to 9999000 and the -i 1 puts a 1 second delay between each attempt nc makes to read and write from network and stdin.

Total hack. Still unsure of root cause. The requests never appear in nc's buffer at all.

**Comment by dfletcher** [comment] 2015-09-08 18:01
Ok well I have a pretty good understanding of the problem now. I'm 100% unsure where to submit a patch to this, nc seems to have been passed around to different authors and I can't find any central repository. The code causing the issue is not one of the Cygwin patches it's in the original sources they used.

The issue is this: the body of the main "loop forever" loop when using -k mode does the following:
1. Call listen(), open a socket.
2. Wait for connection.
3. Handle connection.
4. Close connection.
5. Close socket.

The calls to listen and close the listening socket are happening _inside this loop_. Therefore there is a slice of time between item 5 in my list and looping back around to 2 where **the server is not listening for connections**. Yikes! I suspect Cygwin or Windows is slow to close the socket and/or open a new one. So before it can finish closing and loop again and start listening, browser tries to make the next connection. Hits right at that horrible moment when the server's not available. Browser can't make a connection, server never sees the request. 

Here's a way to fix this by hand for now (you'll need standard build tools like gcc etc).
- Launch Cygwin's setup.exe, install the src package for nc and the "cygport" tool.
- Run `cygport /usr/src/nc.cygport prep`
- Edit /usr/src/nc-1.107-4.x86_64/src/nc/netcat.c
  - Around line 378 move "if (family != AF_UNIX) s = local_listen(host, uport, hints);" **above** the for loop.
  - Around line 414 move "if (family != AF_UNIX) close(s);" **below** the for loop which should end around 420 (after cutting). This leaves the next statement as "else if (uflag)..." remove the "else" so it just starts "if (uflag)...". Won't compile less you do that last bit.
- Run `cygport /usr/src/nc.cygport compile`
- `mv /usr/bin/nc.exe /usr/bin/nc.exe.bak`
- `cp /usr/src/nc-1.107-4.x86_64/build/nc.exe /bin`

[Here is a patch if you don't want to edit netcat.c by hand](http://pastebin.com/raw.php?i=W4VfHCtH). Save it to a file, cd to the src/nc dir where netcat.c lives and `patch < /path/to/netcat.patch`

**Comment by dfletcher** [comment] 2015-09-08 23:35
Might submit the patch to the Cygwin folks. Even though they aren't the source of the issue it does manifest itself on Cygwin in an irritating way. The patch could pretty much drop right into cygport.

**Comment by tarekeldeeb** [comment] 2015-09-10 17:18
Hey,

Sorry just recognized the whole thread.

Thanks a lot for your devotion and support.

Regards,

## Regards,

_Tarek Eldeeb_
Senior Digital Design Engineer
[image: my GPG]
http://pgp.mit.edu:11371/pks/lookup?search=0xF1234BFE&op=index&fingerprint=on
| [image: my LinkedIn] http://linkedin.com/in/tarekeldeeb | [image: my
Tweets] http://twitter.com/tarekeldeeb

2015-09-09 0:35 GMT+01:00 Dave Fletcher notifications@github.com:

**Comment by dfletcher** [comment] 2015-09-15 03:25
There is another possible fix in the 'socat' branch if you want to try it out. I'm away from my Windows machine on a temporary Ubuntu 15.04 laptop for a few days. Seems to work really well on here.

If you install socat (it's available for Cygwin I checked it) the script will prefer to use that instead of nc. I think the way socat works, this whole idea should work a lot better on all platforms really.

I will document how socat works (slightly different than the "theory of operation" on there now) and recommend using that over nc in the main readme. I'll merge it to master branch after I can test on Cygwin later in the week.

**Closed as completed** 2015-09-16 21:27 UTC

**Comment by dfletcher** [comment] 2015-09-16 21:29
OK! Marked it solved. If any Cygwin folks find this thread and are using `nc`, please run setup.exe and install `socat`. The script will prefer to use that if it is available and Socat mode works (slowly but) correctly in Cygwin.
